export const POKEMON_TYPES_JP = [
  { name: 'normal', jp: 'ノーマル' },
  { name: 'fighting', jp: 'かくとう' },
  { name: 'flying', jp: 'ひこう' },
  { name: 'poison', jp: 'どく' },
  { name: 'ground', jp: 'じめん' },
  { name: 'rock', jp: 'いわ' },
  { name: 'bug', jp: 'むし' },
  { name: 'ghost', jp: 'ゴースト' },
  { name: 'steel', jp: 'はがね' },
  { name: 'fire', jp: 'ほのお' },
  { name: 'water', jp: 'みず' },
  { name: 'grass', jp: 'くさ' },
  { name: 'electric', jp: 'でんき' },
  { name: 'psychic', jp: 'エスパー' },
  { name: 'ice', jp: 'こおり' },
  { name: 'dragon', jp: 'ドラゴン' },
  { name: 'dark', jp: 'あく' },
  { name: 'fairy', jp: 'フェアリー' },
]
